spring:
  security:
    oauth2:
      client:
        registration:
          cognito:
            clientId: ${COGNITO_CLIENT_ID}
            clientSecret: ${COGNITO_CLIENT_SECRET}
            scope: openid, profile, email
            clientName: ${COGNITO_CLIENT_NAME}
        provider:
          cognito:
            issuerUri: ${COGNITO_ISSUER_URI}
  cloud:
    aws:
      region:
        static: ${AWS_REGION}

custom:
  use-cognito-as-identity-provider: true
  invitation-codes: ${INVITE_CODES}