server:
  forward-headers-strategy: framework

spring:
  application:
    name: snookerup-webapp
  cloud:
    aws:
      region:
        static: eu-west-2

logging:
  level:
    com.snookerup: DEBUG

custom:
  invitation-codes: CRUCIBLE, 147_BREAK, SNOOKER_CUE

# Will be overwritten by environment variables in AWS
COGNITO_CLIENT_ID: TBD
COGNITO_LOGOUT_URL: TBD
COGNITO_USER_POOL_ID: TBD