# This workflow deploys all resources that are specific to the app, but not the app itself.
name: 03 - Manually create the environment for the application

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

on:
  workflow_dispatch:
    inputs:
      environmentName:
        description: 'The name of the environment in which to deploy the app-specific environment resources.'
        required: true
        default: 'staging'
jobs:
#  No jobs yet