# This workflow deploys all resources that are specific to the app, but not the app itself.
name: 03 - Manually create the environment for the application

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

on:
  workflow_dispatch:
    inputs:
      environmentName:
        description: 'The name of the environment in which to deploy the app-specific environment resources.'
        required: true
        default: 'staging'
jobs:
  deploy-database-stack:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-22.04
    name: Deploy the database stack
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'maven'

      - name: NPM install
        working-directory: cdk
        run: npm install

      - name: Deploy database stack
        working-directory: cdk
        run: npm run database:deploy -- -c environmentName=${{ github.event.inputs.environmentName }}

  deploy-cognito-stack:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-22.04
    name: Deploy the Cognito stack
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'maven'

      - name: NPM install
        working-directory: cdk
        run: npm install

      - name: Deploy Cognito stack
        working-directory: cdk
        run: npm run cognito:deploy -- -c environmentName=${{ github.event.inputs.environmentName }}