# This workflow modifies the previously-created load balancer to serve the app through our domain.
# This needs to run manually, once, after the service is first deployed.
name: 05 - Manually serve the app from the domain

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

on:
  workflow_dispatch:
jobs:
  deploy-domain-stack:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-22.04
    name: Deploy the domain stack
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'maven'

      - name: NPM install
        working-directory: cdk
        run: npm install

      - name: Deploy domain stack
        working-directory: cdk
        run: npm run domain:deploy
